### ISSUE TITLE
ng-canvas-gauges 6.0.0 @ npmjs is goofed

### ISSUE THREAD

**Issue by wayneparrott** [MeetmeLeave/ng-canvas-gauges#23]
The ng-canvas-gauges 6.0.0 at npmjs public catalog is not runnable. Instead of publishing the full git repo as it is now,  you only need to publish the ng-canvas-gauges/lib/ng-canvas-gauges-6.0.0.tgz file. You can build/rebuild this npm publishable file using

      npm run build:package

Then publish to npm with:

     npm login
     npm publish <path>/lib/ng-canvas-gauges-6.X.Y.tgz 

Hope this helps!

**Comment by MeetmeLeave** [comment]
@wayneparrott thanks for raising this, merged your new PR and republished the 6.0.4 version. I really appreciate your help with maintaining the project :)
