### ISSUE TITLE
ng build --prod does not work for ng-canvas-gauges (AOT compilation)

### ISSUE THREAD

**Issue by msteinberger** [MeetmeLeave/ng-canvas-gauges#3]
When using the example "gauge-demo" of this repository (MeetmeLeave/ng-canvas-gauges/example), and building the example for producation the Angular CLI throws the following error:

Cmd: `ng build --prod`

Output: 

```
ERROR in Unexpected value 'LinearGaugeComponent in ng-canvas-gauges-master/example/node_modules/ng-canvas-gauges/lib/linear-gauge.d.ts' declared by the module
 'AppModule in ng-canvas-gauges-master/example/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in ng-canvas-gauges-master\example\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

```

**Comment by andregomars** [comment]
Me too! got same error when following script is executed:
`ng build --prod -vc false -oh none`

Needs help!

**Comment by MeetmeLeave** [comment]
It seems that this issue is generic for the AOT, I spent some time looking into the source and the possible solutions and it seems it will remain for some time.

There is the same issue opened on the Angular repo - https://github.com/angular/angular/issues/15890 I will keep looking for that thread until people will find the ability to resolve it.

**Comment by JuliaRakitina** [comment]
Same issue :(

**Comment by MeetmeLeave** [comment]
Finally, this is fixed with latest library release, to bypass AOT compilations I had to wrap components into the ng module, so this release contains breaking changes. The example project lists how to properly add components to project now.

**Comment by marcossapp** [comment]
Are you sure it's solved?

**Comment by marcossapp** [comment]
I reproduced this steps and the example project did not worked properly as you said.

**Comment by pmeems** [comment]
I had the same error during run-time.
I solved it by deleting the `node_modules` folder inside `\node_modules\ng-canvas-gauges\`
