### ISSUE TITLE
Add a licsense to the respository

### ISSUE THREAD

**Issue by Akkusativobjekt** [MeetmeLeave/ng-canvas-gauges#5]
First of all I want to really appreciate your work on this repository. I would suggest that you add a license to the repo, because this would make it easier and safer to use and could probably increase it's popularity.

Maybe you can get some inspiration from https://choosealicense.com/ 

Keep up the good work!

**Comment by MeetmeLeave** [comment]
Thank you for the kind words, sorry don't have much spare time to track things at the moment on this repo. I have pushed MIT license file.
